### ISSUE TITLE
Is it possible to control parameter of the presets with web MIDI ?

### ISSUE THREAD

**Issue by Jonathhhan** [jberg/butterchurn#26] opened 2019-10-02 03:17 UTC
Hi, thanks for your great work.
I implemented Butterchurn into my experimental website.
It listens to MIDI input and visualizes the played sound.
I wonder if it would be possible to control the parameters of the presets with web MIDI (or at all).
Here is the site if you want to have a look: http://webmidi.handmadeproductions.de

**Comment by jberg** [comment] 2019-10-03 01:08
Hey, thanks! Love seeing new integrations, thanks.

Well, it would be technically possible, but it will be hard and require a decent amount of knowledge of how MilkDrop presets work.

If you want to learn more about MilkDrop presets, I would start here: http://www.geisswerks.com/hosted/milkdrop2/milkdrop_preset_authoring.html

Butterchurn presets are just JSON files, so you could technically setup a MIDI controller, modify the preset JSON based on input and then pass that new preset to butterchurn.

Every preset has a `baseVals` section that defines the initial values for presets.  The problem is that the presets can also write to these values on every frame, so the `baseVals` is really just the starting value many times. So it is up to the preset whether it is updating certain values each frame or just sticking with the value from `baseVals`, so that might make it look like the starting value isn't really doing anything.

Let me know if you give it a try, thanks!

**Comment by Jonathhhan** [comment] 2019-10-03 14:18
thanks for your explanations. i will give it a try, but i will need some time. and i will let you know.
without knowing enough - would it be possible to write the midi values every frame too?

**Comment by jberg** [comment] 2019-10-03 16:59
No, thats not currently possible. Also that would lead to some weird behaviours, but I suppose that still might be better than having no affect.

**Comment by jberg** [comment] 2019-10-04 21:02
Going to close this for now, but feel free to get in touch if you start working on integrating MIDI controls in anyway, thanks!

**Closed by jberg** 2019-10-04 21:02 UTC
